perf: replace express and ws with uWebSockets.js
Picoseconds/sanctuary pull request #20
Opened 2020-09-19 21:58 UTC by Illya9999

replaces express and ws with uWebSockets.js for speed gain, also removes uptimeWS because it can be
used to DOS the server

2020-09-20 01:12 UTC, Picoseconds commented
Thanks for... uh making a DOS script and then fixing it?

2020-09-20 16:13 UTC, Project-Magenta commented
don't console log OOPS on error

2020-09-20 16:31 UTC, Picoseconds commented
Please remove the `console.log('OOPS')` in clientClose()

2020-09-20 21:11 UTC, Picoseconds commented
👌 this seems ready, will have to do some more testing later though

2020-09-30 21:22 UTC, Picoseconds requested changes

2020-09-30 21:22 UTC, Picoseconds commented on src/server.ts
> +app.get('sanctuary', (res: HttpResponse) => {
This code may be subject to a race condition if the client closes the request before the call to `res.end()`. Are you able to test this?

2020-12-08 20:03 UTC, Illya9999 commented on src/server.ts
> +app.get('sanctuary', (res: HttpResponse) => {
I updated it

2026-02-14 09:54 UTC, closed without merging